### ISSUE TITLE
yarn 2.0 - missing webpack@^4.4.0 requested by mini-css-extract-plugin@npm:0.9.0

### ISSUE THREAD

**Issue by aforty** [wickedev/razzle-plugin-less#1]
Hey! Thanks for your work on this, it's been very helpful to me.

Yarn 2.0 is just around the corner (currently at 2.0.0-rc.24) and it seems much stricter around package dependencies. Here is the error when I start razzle with 2.0. I think the fix is to simply add webpack as a peer dependency to this project to fulfill the requirement from `mini-css-extract-plugin`.

Install yarn 2.0 via `npm i -g yarn@berry`.

```
Error: A package is trying to access a peer dependency that should be provided by its direct ancestor but isn't

Required package: webpack (via "webpack")
Required by: mini-css-extract-plugin@virtual:778325a80664340276b28435099ca242920d896fc9874a2055620c09d4b898f308afb660a011f9b80650b3bbadbf669bbd2c456b6876b980021ec810dc8f2aa8#npm:0.9.0 (via /Users/aforty/Code/swill-www/.yarn/$$virtual/mini-css-extract-plugin-virtual-473b92aa2a/0/cache/mini-css-extract-plugin-npm-0.9.0-f8c8899095-1.zip/node_modules/mini-css-extract-plugin/dist/)
```

**Comment by wickedev** [comment]
#

**Comment by wickedev** [comment]
I didn't check if it worked, but I've attached a v5.0.0 tag for PR. https://github.com/wickedev/razzle-plugin-less/tree/v5.0.0
