### ISSUE TITLE
No module factory available for dependency type: CssDependency

### ISSUE THREAD

**Issue by aforty** [wickedev/razzle-plugin-less#2]
Hi,
Me again. I'm getting this error when I try to build for production. When I remove any `@import` for less files the problem goes away.

/edit Nevermind, seems the issue is lies here: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/493

**Comment by wickedev** [comment]
Sorry.  I missed notification mail.  I'll check.  Thank you
